spring:
  datasource:
    url: jdbc:mysql://cinezone.info:4459/food?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: 123456@Abc
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: Asia/Ho_Chi_Minh
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:vaultfood99@gmail.com}
    password: ${MAIL_PASSWORD:oxjd kfus tdhu fqve}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 3000
          writetimeout: 5000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

app:
  jwt:
    secret: ${APP_JWT_SECRET:change-this-to-a-long-random-secret}
    expiration-ms: ${APP_JWT_EXPIRATION_MS:86400000}
    refresh-expiration-ms: ${APP_JWT_REFRESH_EXPIRATION_MS:604800000}
  swagger:
    enabled: true
  email:
    company-name: ${EMAIL_COMPANY_NAME:Healthy Food API}
    support-email: ${EMAIL_SUPPORT_EMAIL:vaultfood99@gmail.com}
  port: ${SERVER_PORT:4458}

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

zalopay:
  app-id: ${ZALOPAY_APP_ID:2553}
  key1: ${ZALOPAY_KEY1:PcY4iZIKFCIdgZvA6ueMcMHHUbRLYjPL}
  key2: ${ZALOPAY_KEY2:kLtgPl8HHhfvMuDHPwKfgfsY4Ydm9eIz}
  endpoint: ${ZALOPAY_ENDPOINT:https://sb-openapi.zalopay.vn/v2/create}
  callback-url: ${ZALOPAY_CALLBACK_URL:http://cinezone.info:4458/api/zalopay/callback}
  redirect-url: ${ZALOPAY_REDIRECT_URL:https://localhost:3000/checkout/success}

firebase:
  config:
    file: ${FIREBASE_CONFIG_FILE:classpath:firebase-service-account.json}
  # Push notification settings
  notification:
    enabled: ${FIREBASE_NOTIFICATION_ENABLED:true}
    # Android notification channel ID
    android:
      channel-id: ${FIREBASE_ANDROID_CHANNEL_ID:order_updates}
      priority: ${FIREBASE_ANDROID_PRIORITY:HIGH}
    # Notification badge color (hex format)
    badge-color: ${FIREBASE_BADGE_COLOR:#52946B}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: list
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 1

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.officefood.healthy_food_api: DEBUG
