name: Build and Publish Java Package (Java 21)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        server-id: github
        server-username: GITHUB_ACTOR
        server-password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and publish package
      run: mvn -B clean deploy --file pom.xml
